# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b956c46952f5266340c32fd8a2d4af8b13e76cc9bf37964911b1742381b5137ea6ae6c3e4dce3eb6f1140d44a86bc12e7e346bb6bef66a211037069c1ef8cffb

test:
  secret_key_base: 4b22253b852fa8daac1e08ab1600995600f22b60a82a51ea7931fdf5ffb1a7e1a57ed1c151228a06fa0da1fe0ff7bb585ac275193a4384ebcdec464e62c65e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
